name: Raymond Lees Jewellery
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Business Gallery site for Raymond Lees Jewellery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a3a29d'
    - '#5c5954'
    - '#3b3632'
    - '#05080d'
  brandStrength: 0.49568642396479845
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
